# file      : bpkg-util/buildfile
# license   : MIT; see accompanying LICENSE file

import mods = libbutl.bash%bash{manifest-parser}

./: exe{bpkg-util-publish bpkg-util-manage} bash{package-archive}

exe{bpkg-util-publish}: in{publish} bash{utility}
exe{bpkg-util-manage}:  in{manage}  bash{utility package-archive}

# Public modules.
#
bash{package-archive}: in{package-archive} $mods

# Private modules.
#
bash{utility}: in{utility}
