# file      : bpkg-rep/buildfile
# copyright : Copyright (c) 2014-2019 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

./: exe{bpkg-rep-publish}

exe{bpkg-rep-publish}: in{publish} bash{utility}

bash{utility}: in{utility}
